### ISSUE TITLE
Find location of ODLC

### ISSUE THREAD

**Issue by fallscameron01** [MissouriMRR/SUAS-2023#10]
# Find location of ODLC

## Problem

Given a contour, find the location of the ODLC.

## Solution

Given a contour, find the location of the ODLC.

**Comment by fallscameron01** [comment]
@EnderDude67 in progress? or should this be reassigned to someone else since you are working on the pipeline?

**Comment by eblake003** [comment]
I somehow missed this. I will start working on this immediately.

**Comment by eblake003** [comment]
`get_coordinates()` in `vision/deskew/camera_distances.py` already solves this issue.
