### ISSUE TITLE
Log Communication Performance Metrics

### ISSUE THREAD

**Issue by fallscameron01** [MissouriMRR/SUAS-2023#119]
# Log Communication Performance Metrics

## Problem

As a part of the flight readiness review video, we will need some performance metrics about our communications.

## Solution

Using `pymavlink`, for a given flight, log to a file some communication performance metrics from MAVLink messages. The relevant MAVLink messages to look for are `SYS_STATUS` and `LINK_NODE_STATUS`.

## Additional Information

This will need to be done by 4/22.

Useful Resources:
- https://www.ardusub.com/developers/pymavlink.html
- https://mavlink.io/en/messages/common.html

**Comment by fallscameron01** [comment]
May not be an issue. Functionality may be built into QGroundControl, needs further investigation.

**Comment by DJDMVP** [comment]
Not an issue functionality is built into the logging of Q Ground Control
