### ISSUE TITLE
Check Feasibility of Realtime Vision Processing

### ISSUE THREAD

**Issue by eblake003** [MissouriMRR/SUAS-2023#131]
# Check Feasibility of Realtime Vision Processing

## Problem

For vision code to be able to run in real time, an image needs to be successfully processed in around 1/10th of a second.

## Solution

Run vision algorithms on an image and measure the time it takes for each step. Find problem areas and places where improvement is needed.

**Comment by cjhr95** [comment]
Total time average: 11.10390575726827
Total time max: 19.120941877365112

Contour average: 4.195128838221232
Contour max: 11.782945156097412

Process shapes average: 1.5165246725082397
Process shapes max: 6.505549669265747

Set shapes average: 0.10123573243618011
Set shapesmax: 0.19373393058776855

Set generic average: 0.0005085170269012451
Set generic max: 0.0013756752014160156

Get odlc average: 0.10059981048107147
Get odlc max: 0.19365191459655762

Find color average: 0.003782578877040318
Find color max: 0.004857301712036133

**Comment by cjhr95** [comment]
Final vision estimations for SUAS 2023 competition
