### ISSUE TITLE
Obstacle Detection

### ISSUE THREAD

**Issue by fallscameron01** [MissouriMRR/SUAS-2023#15]
# Obstacle Detection

## Problem

Need to be able to detect other UAS vehicles and any other obstacles in the vicinity of the UAS.

## Solution

Given an image, determine if an obstacle is nearby to the UAS. Need ability to track obstacles between frames in order to determine if an obstacle is getting closer to the UAS.

**Utilize Ouster spinning LiDAR sensor to detect obstacles.**

## Additional Resources

- Ouster Quick Start Guide Python: https://static.ouster.dev/sdk-docs/python/quickstart.html
- Ouster Python API Documentation: https://static.ouster.dev/sdk-docs/python/api/index.html

**Comment by fallscameron01** [comment]
**Note:** we have purchased and will be using the OS1-32 spinning LiDAR sensor to handle our obstacle detection. See additional resources for Python guide/API.

**Comment by fallscameron01** [comment]
Related to #32

**Comment by cjhr95** [comment]
LiDAR will not be used for Obstacle Detection for SUAS 2024.
