### ISSUE TITLE
Standard Object Contour Gathering

### ISSUE THREAD

**Issue by eblake003** [MissouriMRR/SUAS-2023#154]
# Standard Object Contour Gathering #154

## Problem

Given an image with distinct shapes, get the contours of those shapes for further processing. False positives are allowed and can be filtered out later, we just need to detect the maximum number of actual shapes in the image.

## Solution

Research image processing methods for making shapes distinct and picking them out of an image.

## Additional Information

Key ideas to research might be:
 - edge detection
 - conversion to alternative color spaces
 - thresholding

**Comment by ths51** [comment]
**Note**
Code from #194 filters out contours by size, which can be affected by camera quality and distance from camera. May have to adjust values to fix this discrepancy.
