### ISSUE TITLE
Feasibility of Ardupilot

### ISSUE THREAD

**Issue by fallscameron01** [MissouriMRR/SUAS-2023#29]
# Feasibility of Ardupilot

## Problem

In order to take advantage of the more reliable ExpressLRS for connection to the drone, determine the feasibility of switching to Ardupilot for flight commands.

## Solution

Would need to determine capabilities/equivalency of DroneKit API when compared to our currently-used MavSDK.

## Additional Resources

- https://ardupilot.org/dev/docs/droneapi-tutorial.html

**Comment by carson-williams** [comment]
In short, it would be possible to switch, just would take lots of rewriting code and relearning of all the built in functions and features. As far as I have found, most if not all of the MavSDK features have equivalent features in DroneKit. 
 
The API Reference for DroneKit can be found [here](https://dronekit-python.readthedocs.io/en/latest/automodule.html). This site shows all of the classes, functions, and every other component of the Python DroneKit API. 
 
The only source I can find that recommends MavSDK over DroneKit is PX4, as seen [here](https://docs.px4.io/main/en/robotics/dronekit.html). It still has documentation listed on that page on how to use DroneKit with PX4, but it says that MavSDK has better features, speed, programming language support, and maintenance. 
 
However, ArduPilot has its own built in simulator (called SITL) and its own Mission Planner software, meaning PX4 would not be necessary if this simulator worked well for our uses. ( https://ardupilot.org/dev/docs/simulation-2.html#:~:text=ArduPilot%20provides%20a%20native%20firmware,Mission%20Planner%20for%20SITL%20simulations)

**Comment by fallscameron01** [comment]
@carson-williams @cjhr95 good to close this issue?

**Comment by cjhr95** [comment]
Almost, we can close the issue after Carson gets the ArduPilot simulator setup and we can see it in action.

**Comment by carson-williams** [comment]
Due to the complexity of the process and number of issues I was running into while trying to set up the DroneKit Simulator (SITL), it would not be worth it to switch. It also would be a very lengthy, tedious process to have to learn all the differences between DroneKit and MavSDK and then rewrite all of our code to work with DroneKit.
