### ISSUE TITLE
Get Data from LiDAR

### ISSUE THREAD

**Issue by fallscameron01** [MissouriMRR/SUAS-2023#32]
# Issue Name

## Problem

Retrieve data using our OS1-32 spinning LiDAR sensor for use in obstacle detection and avoidance.

## Solution

Retrieve data using our OS1-32 spinning LiDAR sensor for use in obstacle detection and avoidance.

## Additional Information

- Ouster Quick Start Guide Python: [https://static.ouster.dev/sdk-docs/python/quickstart.html](https://static.ouster.dev/sdk-docs/python/quickstart.html)
- Ouster Python API Documentation: [https://static.ouster.dev/sdk-docs/python/api/index.html](https://static.ouster.dev/sdk-docs/python/api/index.html)

**Comment by fallscameron01** [comment]
Related to #15

**Comment by cjhr95** [comment]
LiDAR integration was not accomplished last year, and we have decided to pursue alternatives for detecting obstacles in issue #15
