### ISSUE TITLE
Air Drop Dropping Mechanism

### ISSUE THREAD

**Issue by fallscameron01** [MissouriMRR/SUAS-2023#4]
# Air Drop Dropping Mechanism

## Problem

Code a way to release the payload when we are stationary above ODLC.

## Solution

Linear actuator or some way with MavSDK

**Comment by fallscameron01** [comment]
solenoid controller?

**Comment by fallscameron01** [comment]
The board: https://www.pololu.com/docs/0J40/7.a
Python API for communicating with controller: https://github.com/jphalip/ticlib

**Comment by Ooglely** [comment]
#89
