### ISSUE TITLE
Emergent Object Dataset

### ISSUE THREAD

**Issue by fallscameron01** [MissouriMRR/SUAS-2023#45]
# Emergent Object Dataset

## Problem

Need a large dataset of images containing "emergent objects" (i.e. people on the ground) for training model.

## Solution

At a flight test, create a large dataset of images satisfying the emergent object as specified in the rules. Annotate images to facilitate model training.

## Additional Information

Images should contain the following:
- the emergent object (a person)
- ODLC objects
- should be taken on asphalt or gravel.

**Comment by cjhr95** [comment]
Photos taken by CTO, currently in Sharepoint
