### ISSUE TITLE
Check if Image contains Airdrop Boundary

### ISSUE THREAD

**Issue by eblake003** [MissouriMRR/SUAS-2023#66]
# Check if Image contains Airdrop Boundary

## Problem

Given the four GPS coordinates of the corners of an image and the points defining the airdrop boundary, check if any part of the image contains the airdrop region.

## Solution

Check if any lines connecting two adjacent image corners intersect with any lines connecting two adjacent points on the airdrop boundary.

## Additional Information

Low priority

**Comment by cjhr95** [comment]
Closed by #149
