### ISSUE TITLE
Check if Location is inside Airdrop Boundary

### ISSUE THREAD

**Issue by eblake003** [MissouriMRR/SUAS-2023#67]
# Check if Candidate ODLC Object is inside Airdrop Boundary

## Problem

Given a GPS location and the points defining the airdrop boundary, check if that location is within the boundary.

## Solution

Use a method similar `cv2.pointPolygonTest()` to check if the point is inside the boundary contour.

## Additional Information

Low priority

**Comment by cjhr95** [comment]
Closed by #149
