### ISSUE TITLE
LiDAR Flight-Vision Pipeline

### ISSUE THREAD

**Issue by fallscameron01** [MissouriMRR/SUAS-2023#92]
# LiDAR Flight-Vision Pipeline

## Problem

Need ability for flight and vision to communicate information obtained from the LiDAR.

## Solution

Need pipeline object that will run vision code on LiDAR data taken during the competition.

## Additional Information

This pipeline will run object detection algorithms in order to determine the locations of obstacles around the drone while performing the competition.

**Comment by cjhr95** [comment]
We have decided not to use LiDAR for the competition moving forward.
